# Generated by Django 3.2.8 on 2021-11-04 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenURL',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(218340105584895, message='MAX_ERROR'), django.core.validators.MinValueValidator(1000000, message='MIN_ERROR')])),
                ('url', models.URLField(max_length=1000, unique=True)),
            ],
        ),
    ]
