URL_ENC = "url-enc"
BASE62 = 62
BASE62_TABLE = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

# validator error message for ShortenURL
VALID_ERR_MSG_MAX = "MAX_ERROR"
VALID_ERR_MSG_MIN = "MIN_ERROR"
VALID_ERR_MSG_URL = "URL_ERROR"
